Repository masters2023-2nd-project-02/second-hand, pull requests merged in 2023-06, with the labels that each got.

#27 [FE] Chore: 초기 세팅 완료
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc
  fe/.storybook/main.ts
  fe/.storybook/preview.tsx
  fe/README.md
  fe/craco.config.js
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.test.tsx
  fe/src/App.tsx
  fe/src/assets/account.svg
  fe/src/assets/arrowUp.svg
  fe/src/assets/camera.svg
  fe/src/assets/cancel.svg
  fe/src/assets/category.svg
  fe/src/assets/chevronDown.svg
  fe/src/assets/chevronLeft.svg
  fe/src/assets/home.svg
  fe/src/assets/keyboard.svg
  fe/src/assets/like.svg
  fe/src/assets/message.svg
  fe/src/assets/more.svg
  fe/src/assets/orderCircle.svg
  fe/src/assets/plus.svg
  fe/src/assets/search.svg
  fe/src/assets/soldList.svg
  fe/src/assets/townSetting.svg
  fe/src/index.tsx
  fe/src/setupTests.ts
  fe/src/styles/GlobalStyles.style.ts
  fe/src/styles/colors.ts
  fe/src/styles/fonts.ts
  fe/src/styles/styled.d.ts
  fe/src/styles/theme.ts
  fe/tsconfig.json
  fe/tsconfig.paths.json
Labels: 🔧 chore, 🧑‍💻 FE

#38 [FE] Feat: 공통 컴포넌트 - ListItem 구현
  fe/.storybook/preview.tsx
  fe/package.json
  fe/src/components/common/ListItem/ListItem.stories.tsx
  fe/src/components/common/ListItem/ListItem.style.ts
  fe/src/components/common/ListItem/index.tsx
Labels: 🧑‍💻 FE, ✨ feat, ✅ test, 🙋🏻 review

#39 [FE] Feat: 공통 컴포넌트 - Tab Bar 구현
  fe/src/components/common/TabBars/MainTabBar/MainTabBar.stories.tsx
  fe/src/components/common/TabBars/MainTabBar/MainTabBar.style.ts
  fe/src/components/common/TabBars/MainTabBar/index.tsx
  fe/src/components/common/TabBars/SaleTabBar/SaleTabBar.stories.tsx
  fe/src/components/common/TabBars/SaleTabBar/SaleTabBar.style.ts
  fe/src/components/common/TabBars/SaleTabBar/index.tsx
  fe/src/styles/GlobalStyles.style.ts
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#44 [FE] 1주차 리뷰를 위한 Merge 풀리퀘
  fe/.storybook/main.ts
  fe/.storybook/preview.tsx
  fe/craco.config.js
  fe/package-lock.json
  fe/package.json
  fe/src/assets/account.svg
  fe/src/assets/arrowUp.svg
  fe/src/assets/camera.svg
  fe/src/assets/cancel.svg
  fe/src/assets/category.svg
  fe/src/assets/chevronDown.svg
  fe/src/assets/chevronLeft.svg
  fe/src/assets/home.svg
  fe/src/assets/keyboard.svg
  fe/src/assets/like.svg
  fe/src/assets/message.svg
  fe/src/assets/more.svg
  fe/src/assets/orderCircle.svg
  fe/src/assets/plus.svg
  fe/src/assets/search.svg
  fe/src/assets/soldList.svg
  fe/src/assets/townSetting.svg
  fe/src/components/common/Icon/Icon.stories.tsx
  fe/src/components/common/Icon/IconComponents.tsx
  fe/src/components/common/Icon/custom.d.ts
  fe/src/components/common/Icon/index.tsx
  fe/src/components/common/ListItem/ListItem.stories.tsx
  fe/src/components/common/ListItem/ListItem.style.ts
  fe/src/components/common/ListItem/index.tsx
  fe/src/components/common/TabBars/MainTabBar/MainTabBar.stories.tsx
  fe/src/components/common/TabBars/MainTabBar/MainTabBar.style.ts
  fe/src/components/common/TabBars/MainTabBar/index.tsx
  fe/src/components/common/TabBars/SaleTabBar/SaleTabBar.stories.tsx
  fe/src/components/common/TabBars/SaleTabBar/SaleTabBar.style.ts
  fe/src/components/common/TabBars/SaleTabBar/index.tsx
  fe/src/styles/GlobalStyles.style.ts
  fe/tsconfig.json
Labels: 🧑‍💻 FE

#45 [FE] Refactor: 공통 컴포넌트 - ListItem 구현
  fe/src/components/common/ListItem/ListItem.stories.tsx
  fe/src/components/common/ListItem/ListItem.style.ts
  fe/src/components/common/ListItem/index.tsx
Labels: 🧑‍💻 FE, ♻️ refactoring

#46 [FE] Chore: 리뷰 위해 `dev-fe`로 머지
  fe/src/components/common/ListItem/ListItem.stories.tsx
  fe/src/components/common/ListItem/ListItem.style.ts
  fe/src/components/common/ListItem/index.tsx
Labels: 🧑‍💻 FE

#50 [FE] feat: getTimeAgo 유틸함수 작성 및 테스트
  fe/src/components/common/ListItem/ListItem.stories.tsx
  fe/src/components/common/ListItem/index.tsx
  fe/src/utils/getTimeAgo/getTimeAgo.test.ts
  fe/src/utils/getTimeAgo/index.ts
Labels: 🧑‍💻 FE, ✨ feat, ✅ test, 🙋🏻 review

#51 [FE] Feat: 버튼 컴포넌트 작성
  fe/src/components/common/Buttons/Button/Button.stories.tsx
  fe/src/components/common/Buttons/Button/Button.style.ts
  fe/src/components/common/Buttons/Button/index.tsx
  fe/src/components/common/Buttons/CircleButton/CircleButton.stories.tsx
  fe/src/components/common/Buttons/CircleButton/CircleButton.style.ts
  fe/src/components/common/Buttons/CircleButton/index.tsx
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#63 [FE] Refactor: 1주차 코드리뷰 반영
  fe/craco.config.js
  fe/craco.config.ts
  fe/package-lock.json
  fe/package.json
  fe/tsconfig.json
Labels: 🧑‍💻 FE, ♻️ refactoring

#69 [FE] Refactor: 아토믹 디자인에 맞춰 directory 구조 변경 및 path 변경
  fe/craco.config.js
  fe/src/components/atoms/Buttons/Button/Button.stories.tsx
  fe/src/components/atoms/Buttons/Button/Button.style.ts
  fe/src/components/atoms/Buttons/Button/index.tsx
  fe/src/components/atoms/Buttons/CircleButton/CircleButton.stories.tsx
  fe/src/components/atoms/Buttons/CircleButton/CircleButton.style.ts
  fe/src/components/atoms/Buttons/CircleButton/index.tsx
  fe/src/components/common/Icon/Icon.stories.tsx
  fe/src/components/common/Icon/IconComponents.tsx
  fe/src/components/common/Icon/custom.d.ts
  fe/src/components/common/Icon/index.tsx
  fe/src/components/molecules/ListItem/ListItem.stories.tsx
  fe/src/components/molecules/ListItem/ListItem.style.ts
  fe/src/components/molecules/ListItem/index.tsx
  fe/src/components/molecules/TabBars/ChatTabBar/ChatTabBar.stories.tsx
  fe/src/components/molecules/TabBars/ChatTabBar/ChatTabBar.style.ts
  fe/src/components/molecules/TabBars/ChatTabBar/index.tsx
  fe/src/components/molecules/TabBars/DetailTabBar/DetailTabBar.stories.tsx
  fe/src/components/molecules/TabBars/DetailTabBar/DetailTabBar.style.ts
  fe/src/components/molecules/TabBars/DetailTabBar/index.tsx
  fe/src/components/molecules/TabBars/MainTabBar/MainTabBar.stories.tsx
  fe/src/components/molecules/TabBars/MainTabBar/MainTabBar.style.ts
  fe/src/components/molecules/TabBars/MainTabBar/index.tsx
  fe/src/components/molecules/TabBars/SaleTabBar/SaleTabBar.stories.tsx
  fe/src/components/molecules/TabBars/SaleTabBar/SaleTabBar.style.ts
  fe/src/components/molecules/TabBars/SaleTabBar/index.tsx
  fe/tsconfig.json
  fe/tsconfig.paths.json
Labels: 🧑‍💻 FE, ♻️ refactoring

#76 [FE] Feat: 공통 컴포넌트 - Chip 완성
  fe/src/components/atoms/Chip/Chip.stories.tsx
  fe/src/components/atoms/Chip/Chip.style.ts
  fe/src/components/atoms/Chip/index.tsx
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#73 [FE] Feat: Input 컴포넌트 구현
  fe/src/components/atoms/Inputs/ImageInput/ImageInput.stories.tsx
  fe/src/components/atoms/Inputs/ImageInput/ImageInput.style.ts
  fe/src/components/atoms/Inputs/ImageInput/index.tsx
  fe/src/components/atoms/Inputs/TextInput/TextInput.stories.tsx
  fe/src/components/atoms/Inputs/TextInput/TextInput.style.ts
  fe/src/components/atoms/Inputs/TextInput/index.tsx
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#79 [FE] Feat: Chips 컴포넌트 구현
  fe/src/components/atoms/Chip/index.tsx
  fe/src/components/molecules/Chips/Chips.stories.tsx
  fe/src/components/molecules/Chips/Chips.style.ts
  fe/src/components/molecules/Chips/index.tsx
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#80 [FE] Feat: common component 배포를 위한 중간 머지
  fe/src/components/atoms/Buttons/Button/Button.stories.tsx
  fe/src/components/atoms/Buttons/CircleButton/CircleButton.stories.tsx
  fe/src/components/atoms/Chip/Chip.stories.tsx
  fe/src/components/atoms/Chip/Chip.style.ts
  fe/src/components/atoms/Chip/index.tsx
  fe/src/components/atoms/Icon/Icon.stories.tsx
  fe/src/components/atoms/Inputs/ImageInput/ImageInput.stories.tsx
  fe/src/components/atoms/Inputs/ImageInput/ImageInput.style.ts
  fe/src/components/atoms/Inputs/ImageInput/index.tsx
  fe/src/components/atoms/Inputs/TextInput/TextInput.stories.tsx
  fe/src/components/atoms/Inputs/TextInput/TextInput.style.ts
  fe/src/components/atoms/Inputs/TextInput/index.tsx
  fe/src/components/molecules/Chips/Chips.stories.tsx
  fe/src/components/molecules/Chips/Chips.style.ts
  fe/src/components/molecules/Chips/index.tsx
  fe/src/components/molecules/ListItem/ListItem.stories.tsx
  fe/src/components/molecules/Modal/Modal.stories.tsx
  fe/src/components/molecules/Modal/Modal.style.ts
  fe/src/components/molecules/Modal/index.tsx
  fe/src/components/molecules/TabBars/ChatTabBar/ChatTabBar.stories.tsx
  fe/src/components/molecules/TabBars/DetailTabBar/DetailTabBar.stories.tsx
  fe/src/components/molecules/TabBars/MainTabBar/MainTabBar.stories.tsx
  fe/src/components/molecules/TabBars/SaleTabBar/SaleTabBar.stories.tsx
  fe/src/hooks/useOutsideClick.ts
Labels: 🧑‍💻 FE, ✨ feat

#92 [FE] Feat: Dropdown 컴포넌트 구현
  fe/src/components/molecules/Dropdown/Dropdown.stories.tsx
  fe/src/components/molecules/Dropdown/Dropdown.style.ts
  fe/src/components/molecules/Dropdown/index.tsx
  fe/src/styles/fonts.ts
Labels: 🧑‍💻 FE, ✨ feat

#113 [FE] Feat: Navbar 컴포넌트 구현
  fe/src/components/atoms/Buttons/Button/Button.style.ts
  fe/src/components/molecules/Navbar/Navbar.stories.tsx
  fe/src/components/molecules/Navbar/Navbar.style.ts
  fe/src/components/molecules/Navbar/index.tsx
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#108 [FE] Feat: 로그인 페이지 구현
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/apis/axiosSetting.ts
  fe/src/assets/github.svg
  fe/src/components/atoms/Icon/IconComponents.tsx
  fe/src/constants/API.ts
  fe/src/constants/routerPath.ts
  fe/src/pages/Auth/index.tsx
  fe/src/pages/Login/Login.style.ts
  fe/src/pages/Login/index.tsx
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#117 [FE] Refactor: 글로벌 스타일 설정
  fe/src/apis/axiosSetting.ts
  fe/src/components/molecules/TabBars/ChatTabBar/ChatTabBar.style.ts
  fe/src/components/molecules/TabBars/DetailTabBar/DetailTabBar.style.ts
  fe/src/components/molecules/TabBars/MainTabBar/MainTabBar.style.ts
  fe/src/components/molecules/TabBars/SaleTabBar/SaleTabBar.style.ts
  fe/src/pages/Login/Login.style.ts
  fe/src/styles/GlobalStyles.style.ts
Labels: 🧑‍💻 FE, ♻️ refactoring

#118 [FE] Feat: common 컴포넌트 구현 완료
  fe/src/components/atoms/Buttons/Button/Button.style.ts
  fe/src/components/molecules/Dropdown/Dropdown.stories.tsx
  fe/src/components/molecules/Dropdown/Dropdown.style.ts
  fe/src/components/molecules/Dropdown/index.tsx
  fe/src/components/molecules/Navbar/Navbar.stories.tsx
  fe/src/components/molecules/Navbar/Navbar.style.ts
  fe/src/components/molecules/Navbar/index.tsx
  fe/src/styles/fonts.ts
Labels: 🧑‍💻 FE, ✨ feat

#121 [FE] Feat: 홈 메인 페이지 구현
  fe/src/App.tsx
  fe/src/components/molecules/Dropdown/Dropdown.style.ts
  fe/src/components/molecules/ListItem/ListItem.stories.tsx
  fe/src/components/molecules/ListItem/ListItem.style.ts
  fe/src/components/molecules/ListItem/index.tsx
  fe/src/components/molecules/Navbar/Navbar.style.ts
  fe/src/components/molecules/TabBars/DetailTabBar/DetailTabBar.stories.tsx
  fe/src/components/molecules/TabBars/DetailTabBar/index.tsx
  fe/src/components/molecules/TabBars/MainTabBar/index.tsx
  fe/src/pages/Auth/index.tsx
  fe/src/pages/Home/HomeMain/HomeMain.style.ts
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Home/HomeMain/mockData.ts
  fe/src/styles/PageTemplate.style.ts
  fe/src/utils/convertPriceFormat.ts
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#130 [FE] Feat: 상품 등록 페이지 중간 merge
  fe/src/App.tsx
  fe/src/components/Login/LoginHeader/index.tsx
  fe/src/components/Login/LoginMain/LoginMain.style.ts
  fe/src/components/Login/LoginMain/index.tsx
  fe/src/components/atoms/Buttons/Button/Button.style.ts
  fe/src/components/molecules/ListItem/ListItem.style.ts
  fe/src/components/molecules/TabBars/MainTabBar/MainTabBar.style.ts
  fe/src/components/molecules/TabBars/MainTabBar/index.tsx
  fe/src/hooks/useCurrentLocation.ts
  fe/src/hooks/useCurrentRegion.ts
  fe/src/pages/Login/index.tsx
  fe/src/pages/Sale/Sale.style.ts
  fe/src/pages/Sale/index.tsx
  fe/src/styles/PageTemplate.style.ts
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#135 [FE] Feat: 이미지 미리보기 컴포넌트 page-sale로 머지
  fe/src/components/atoms/Inputs/ImageInput/ImageInput.style.ts
  fe/src/components/atoms/Inputs/ImageInput/index.tsx
  fe/src/components/molecules/ImagePreviews/ImagePreviews.stories.tsx
  fe/src/components/molecules/ImagePreviews/ImagePreviews.style.ts
  fe/src/components/molecules/ImagePreviews/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#145 [FE] page-sale 브랜치로 머지
  fe/src/App.tsx
  fe/src/assets/Icons/checkmark.svg
  fe/src/components/Sale/SaleCategory/SaleCategoryHeader/SaleCategoryHeader.style.ts
  fe/src/components/Sale/SaleCategory/SaleCategoryHeader/index.tsx
  fe/src/components/Sale/SaleCategory/SaleCategoryMain/SaleCategoryMain.style.ts
  fe/src/components/Sale/SaleCategory/SaleCategoryMain/index.tsx
  fe/src/components/Sale/SaleMain/SaleMain.style.ts
  fe/src/components/Sale/SaleMain/index.tsx
  fe/src/components/atoms/Icon/IconComponents.tsx
  fe/src/constants/categories.ts
  fe/src/pages/Sale/SaleCategory/index.tsx
  fe/src/pages/Sale/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#147 [FE] Feat: session Storage 이용해서 쓰던 글 불러오기 성공
  fe/src/components/Sale/SaleHeader/index.tsx
  fe/src/components/Sale/SaleMain/index.tsx
  fe/src/constants/categories.ts
  fe/src/pages/Sale/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#144 [FE] Feat: 홈 메인 페이지 FAB 버튼 추가 및 무한 스크롤 구현
  fe/src/apis/instances/mockAxiosFetch.ts
  fe/src/components/molecules/Dropdown/index.tsx
  fe/src/pages/Home/HomeMain/HomeMain.style.ts
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/styles/PageTemplate.style.ts
  fe/tsconfig.paths.json
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#136 [FE] Feat: 이미지 미리보기 컴포넌트 완성
  fe/src/components/atoms/Inputs/ImageInput/ImageInput.style.ts
  fe/src/components/atoms/Inputs/ImageInput/index.tsx
  fe/src/components/molecules/ImagePreviews/ImagePreviews.stories.tsx
  fe/src/components/molecules/ImagePreviews/ImagePreviews.style.ts
  fe/src/components/molecules/ImagePreviews/index.tsx
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#160 [FE] Feat: 홈 카테고리 페이지 완성
  fe/public/assets/baby-book.png
  fe/public/assets/baby.png
  fe/public/assets/beauty.png
  fe/public/assets/book.png
  fe/public/assets/buy.png
  fe/public/assets/car.png
  fe/public/assets/digital.png
  fe/public/assets/domestic.png
  fe/public/assets/etc.png
  fe/public/assets/furniture.png
  fe/public/assets/game.png
  fe/public/assets/kitchen.png
  fe/public/assets/man-apparel.png
  fe/public/assets/pet.png
  fe/public/assets/plant.png
  fe/public/assets/processed-foods.png
  fe/public/assets/sports.png
  fe/public/assets/ticket.png
  fe/public/assets/woman-accessories.png
  fe/public/assets/woman-apparel.png
  fe/src/App.tsx
  fe/src/components/Home/HomeCategory/HomeCategoryHeader/HomeCategoryHeader.style.ts
  fe/src/components/Home/HomeCategory/HomeCategoryHeader/index.tsx
  fe/src/components/Home/HomeCategory/HomeCategoryMain/HomeCategoryMain.style.ts
  fe/src/components/Home/HomeCategory/HomeCategoryMain/index.tsx
  fe/src/components/Sale/SaleMain/SaleMain.style.ts
  fe/src/constants/categories.ts
  fe/src/pages/Home/HomeCategory/index.tsx
  fe/src/pages/Home/HomeMain/HomeMain.style.ts
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/styles/PageTemplate.style.ts
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#165 [FE] Feat: 도시 설정 페이지 구현
  fe/src/App.tsx
  fe/src/components/Home/TownSetting/TownSettingHeader/TownSettingHeader.style.ts
  fe/src/components/Home/TownSetting/TownSettingHeader/index.tsx
  fe/src/components/Home/TownSetting/TownSettingMain/TownSettingMain.style.ts
  fe/src/components/Home/TownSetting/TownSettingMain/index.tsx
  fe/src/components/Home/TownSetting/TwonSettingFooter/TownSettingFooter.style.ts
  fe/src/components/Home/TownSetting/TwonSettingFooter/index.tsx
  fe/src/components/molecules/Dropdown/index.tsx
  fe/src/components/molecules/ListItem/ListItem.style.ts
  fe/src/constants/API.ts
  fe/src/pages/Auth/index.tsx
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Home/TownSetting/index.tsx
  fe/src/pages/Login/index.tsx
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#167 [FE] Feat: 도시 검색 페이지 구현
  fe/src/App.tsx
  fe/src/components/Home/HomeMain/HomeMainHeader/index.tsx
  fe/src/components/Home/HomeMain/HomeMainMain/HomeMainMain.style.ts
  fe/src/components/Home/HomeMain/HomeMainMain/index.tsx
  fe/src/components/Home/TownSearching/TownSearchingFooter/TownSearchingFooter.style.ts
  fe/src/components/Home/TownSearching/TownSearchingFooter/index.tsx
  fe/src/components/Home/TownSearching/TownSearchingHeader/TownSearchingHeader.style.ts
  fe/src/components/Home/TownSearching/TownSearchingHeader/index.tsx
  fe/src/components/Home/TownSearching/TownSearchingMain/index.tsx
  fe/src/components/Home/TownSetting/TownSettingFooter/TownSettingFooter.style.ts
  fe/src/components/Home/TownSetting/TownSettingFooter/index.tsx
  fe/src/components/Home/TownSetting/TownSettingHeader/index.tsx
  fe/src/components/molecules/Dropdown/index.tsx
  fe/src/hooks/useIntersectionObserver.ts
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Home/TownSearching/index.tsx
  fe/src/pages/Home/TownSetting/index.tsx
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#177 [FE] Feat: 판매 목록 페이지 구현
  fe/src/App.tsx
  fe/src/components/SalesHistory/SalesHistoryHeader/SalesHistoryHeader.style.ts
  fe/src/components/SalesHistory/SalesHistoryHeader/index.tsx
  fe/src/components/SalesHistory/SalesHistoryMain/SalesHistoryMain.style.ts
  fe/src/components/SalesHistory/SalesHistoryMain/index.tsx
  fe/src/components/molecules/SegmentedControl/SegmentedButton/SegmentedButton.style.ts
  fe/src/components/molecules/SegmentedControl/SegmentedButton/index.tsx
  fe/src/components/molecules/SegmentedControl/SegmentedControl.stories.tsx
  fe/src/components/molecules/SegmentedControl/SegmentedControl.style.ts
  fe/src/components/molecules/SegmentedControl/index.tsx
  fe/src/components/molecules/TabBars/MainTabBar/MainTabBar.stories.tsx
  fe/src/components/molecules/TabBars/MainTabBar/index.tsx
  fe/src/constants/API.ts
  fe/src/hooks/useIntersectionObserver.ts
  fe/src/pages/Auth/index.tsx
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Home/HomeMain/mockData.ts
  fe/src/pages/Login/index.tsx
  fe/src/pages/Sale/index.tsx
  fe/src/pages/SalesHistory/index.tsx
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#204 [FE] Feat: 관심 목록 페이지 완성
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.tsx
  fe/src/apis/api/like.ts
  fe/src/components/Home/TownSetting/TownSettingMain/index.tsx
  fe/src/components/Like/LikeHeader/LikeHeader.style.ts
  fe/src/components/Like/LikeHeader/index.tsx
  fe/src/components/Like/LikeMain/LikeMain.style.ts
  fe/src/components/Like/LikeMain/index.tsx
  fe/src/components/Login/LoginMain/LoginMain.style.ts
  fe/src/components/Login/LoginMain/index.tsx
  fe/src/components/molecules/Chips/Chips.stories.tsx
  fe/src/components/molecules/Chips/index.tsx
  fe/src/constants/API.ts
  fe/src/pages/Like/index.tsx
  fe/src/type/productsType.ts
  fe/tsconfig.paths.json
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#206 [FE] Refactor: 로그인 로직 수정 및 라우트 매직넘버 제거
  fe/src/App.tsx
  fe/src/constants/routerPath.ts
  fe/src/index.tsx
  fe/src/pages/Auth/index.tsx
Labels: 🧑‍💻 FE, ♻️ refactoring, 🙋🏻 review

#208 [FE] Feat: 스켈레톤 페이지 완성
  fe/src/components/Loading/Skeleton/SkeletonHeader/SkeletonHeader.style.ts
  fe/src/components/Loading/Skeleton/SkeletonHeader/index.tsx
  fe/src/components/Loading/Skeleton/SkeletonListItem/SkeletonListItem.style.ts
  fe/src/components/Loading/Skeleton/SkeletonListItem/index.tsx
  fe/src/pages/Like/index.tsx
  fe/src/pages/Loading/Skeleton/Skeleton.stories.tsx
  fe/src/pages/Loading/Skeleton/Skeleton.style.ts
  fe/src/pages/Loading/Skeleton/index.jsx
Labels: 🧑‍💻 FE, ✨ feat, 🙋🏻 review

#214 [FE] Feat: 3주차까지 구현 내용 release 브랜치에 merge
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.tsx
  fe/src/apis/api/like.ts
  fe/src/apis/api/saleHistory.ts
  fe/src/components/Home/HomeMain/HomeMainMain/index.tsx
  fe/src/components/Home/TownSetting/TownSettingFooter/TownSettingFooter.style.ts
  fe/src/components/Home/TownSetting/TownSettingMain/index.tsx
  fe/src/components/Like/LikeHeader/LikeHeader.style.ts
  fe/src/components/Like/LikeHeader/index.tsx
  fe/src/components/Like/LikeMain/LikeMain.style.ts
  fe/src/components/Like/LikeMain/index.tsx
  fe/src/components/Loading/Skeleton/SkeletonHeader/SkeletonHeader.style.ts
  fe/src/components/Loading/Skeleton/SkeletonHeader/index.tsx
  fe/src/components/Loading/Skeleton/SkeletonListItem/SkeletonListItem.style.ts
  fe/src/components/Loading/Skeleton/SkeletonListItem/index.tsx
  fe/src/components/Login/LoginMain/LoginMain.style.ts
  fe/src/components/Login/LoginMain/index.tsx
  fe/src/components/SalesHistory/SalesHistoryMain/index.tsx
  fe/src/components/molecules/Chips/Chips.stories.tsx
  fe/src/components/molecules/Chips/index.tsx
  fe/src/components/molecules/ListItem/ListItem.stories.tsx
  fe/src/components/molecules/ListItem/index.tsx
  fe/src/constants/API.ts
  fe/src/constants/routerPath.ts
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Like/index.tsx
  fe/src/pages/Loading/Skeleton/Skeleton.stories.tsx
  fe/src/pages/Loading/Skeleton/Skeleton.style.ts
  fe/src/pages/Loading/Skeleton/index.jsx
  fe/src/pages/SalesHistory/index.tsx
  fe/src/type/productsType.ts
  fe/src/utils/getStatusWord/index.ts
  fe/tsconfig.paths.json
Labels: 🧑‍💻 FE, ✨ feat

#223 [FE] Feat: 상품 판매 페이지 POST 할 수 있게끔 변경
  fe/src/apis/api/sale.ts
  fe/src/components/Sale/SaleHeader/index.tsx
  fe/src/components/Sale/SaleMain/SaleMain.style.ts
  fe/src/components/Sale/SaleMain/index.tsx
  fe/src/components/atoms/Buttons/Button/Button.style.ts
  fe/src/components/atoms/Buttons/Button/index.tsx
  fe/src/components/atoms/Inputs/ImageInput/index.tsx
  fe/src/components/molecules/ImagePreviews/ImagePreviews.stories.tsx
  fe/src/components/molecules/ImagePreviews/ImagePreviews.style.ts
  fe/src/components/molecules/ImagePreviews/index.tsx
  fe/src/constants/API.ts
  fe/src/constants/routerPath.ts
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Sale/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#236 [FE] Feat: 판매 등록 페이지 완성
  fe/src/apis/api/like.ts
  fe/src/apis/api/productDetail.ts
  fe/src/apis/instances/axiosFetch.ts
  fe/src/components/Sale/SaleHeader/SaleHeader.style.ts
  fe/src/components/Sale/SaleHeader/index.tsx
  fe/src/components/Sale/SaleMain/index.tsx
  fe/src/index.tsx
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Sale/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#224 [FE] Feat: 상품 상세 페이지 구현
  fe/src/App.tsx
  fe/src/components/Detail/DetailHeader/DetailHeader.style.ts
  fe/src/components/Detail/DetailHeader/index.tsx
  fe/src/components/Detail/DetailMain/DetailMain.style.ts
  fe/src/components/Detail/DetailMain/index.tsx
  fe/src/components/Home/HomeMain/HomeMainMain/index.tsx
  fe/src/components/Like/LikeMain/index.tsx
  fe/src/components/SalesHistory/SalesHistoryMain/index.tsx
  fe/src/components/atoms/Buttons/Button/Button.style.ts
  fe/src/components/molecules/Carousel/Carousel.stories.tsx
  fe/src/components/molecules/Carousel/Carousel.style.ts
  fe/src/components/molecules/Carousel/index.tsx
  fe/src/components/molecules/ListItem/index.tsx
  fe/src/components/molecules/Navbar/Navbar.style.ts
  fe/src/components/molecules/Navbar/index.tsx
  fe/src/components/molecules/TabBars/DetailTabBar/index.tsx
  fe/src/pages/Detail/index.tsx
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/styles/PageTemplate.style.ts
  fe/src/type/productsType.ts
Labels: 🧑‍💻 FE, ✨ feat

#237 [FE] release 브랜치로 지금까지 작업한 내용 merge
  fe/src/App.tsx
  fe/src/apis/api/like.ts
  fe/src/apis/api/productDetail.ts
  fe/src/apis/api/sale.ts
  fe/src/apis/api/saleHistory.ts
  fe/src/apis/instances/axiosFetch.ts
  fe/src/components/Detail/DetailHeader/DetailHeader.style.ts
  fe/src/components/Detail/DetailHeader/index.tsx
  fe/src/components/Detail/DetailMain/DetailMain.style.ts
  fe/src/components/Detail/DetailMain/index.tsx
  fe/src/components/Home/HomeMain/HomeMainMain/index.tsx
  fe/src/components/Like/LikeMain/index.tsx
  fe/src/components/Loading/Skeleton/SkeletonListItem/SkeletonListItem.style.ts
  fe/src/components/Sale/SaleHeader/SaleHeader.style.ts
  fe/src/components/Sale/SaleHeader/index.tsx
  fe/src/components/Sale/SaleMain/SaleMain.style.ts
  fe/src/components/Sale/SaleMain/index.tsx
  fe/src/components/SalesHistory/SalesHistoryMain/index.tsx
  fe/src/components/atoms/Buttons/Button/Button.style.ts
  fe/src/components/atoms/Buttons/Button/index.tsx
  fe/src/components/atoms/Inputs/ImageInput/index.tsx
  fe/src/components/molecules/Carousel/Carousel.stories.tsx
  fe/src/components/molecules/Carousel/Carousel.style.ts
  fe/src/components/molecules/Carousel/index.tsx
  fe/src/components/molecules/ImagePreviews/ImagePreviews.stories.tsx
  fe/src/components/molecules/ImagePreviews/ImagePreviews.style.ts
  fe/src/components/molecules/ImagePreviews/index.tsx
  fe/src/components/molecules/ListItem/index.tsx
  fe/src/components/molecules/Navbar/Navbar.style.ts
  fe/src/components/molecules/Navbar/index.tsx
  fe/src/components/molecules/TabBars/DetailTabBar/index.tsx
  fe/src/constants/API.ts
  fe/src/constants/routerPath.ts
  fe/src/index.tsx
  fe/src/pages/Detail/index.tsx
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Like/index.tsx
  fe/src/pages/Loading/Skeleton/Skeleton.style.ts
  fe/src/pages/Loading/Skeleton/index.jsx
  fe/src/pages/Sale/index.tsx
  fe/src/pages/SalesHistory/index.tsx
  fe/src/styles/PageTemplate.style.ts
  fe/src/type/productsType.ts
Labels: 🧑‍💻 FE, ✨ feat

#244 [FE] Refactor: api 수정
  fe/src/components/Home/HomeMain/HomeMainHeader/index.tsx
  fe/src/components/Home/HomeMain/HomeMainMain/index.tsx
  fe/src/components/molecules/Dropdown/Dropdown.stories.tsx
  fe/src/components/molecules/Dropdown/index.tsx
  fe/src/components/molecules/ListItem/index.tsx
  fe/src/pages/Home/HomeMain/index.tsx
Labels: 🧑‍💻 FE, ♻️ refactoring

#249 [FE] Feat: 지금까지 구현한 기능 dev-fe에 merge
  fe/public/index.html
  fe/src/App.tsx
  fe/src/apis/api/like.ts
  fe/src/apis/api/productDetail.ts
  fe/src/apis/api/sale.ts
  fe/src/apis/api/saleHistory.ts
  fe/src/apis/instances/axiosFetch.ts
  fe/src/assets/Icons/fillHeart.svg
  fe/src/components/Detail/DetailHeader/DetailHeader.style.ts
  fe/src/components/Detail/DetailHeader/index.tsx
  fe/src/components/Detail/DetailMain/DetailMain.style.ts
  fe/src/components/Detail/DetailMain/index.tsx
  fe/src/components/Home/HomeMain/HomeMainHeader/index.tsx
  fe/src/components/Home/HomeMain/HomeMainMain/index.tsx
  fe/src/components/Like/LikeMain/index.tsx
  fe/src/components/Loading/Skeleton/SkeletonListItem/SkeletonListItem.style.ts
  fe/src/components/Sale/SaleHeader/SaleHeader.style.ts
  fe/src/components/Sale/SaleHeader/index.tsx
  fe/src/components/Sale/SaleMain/SaleMain.style.ts
  fe/src/components/Sale/SaleMain/index.tsx
  fe/src/components/SalesHistory/SalesHistoryMain/index.tsx
  fe/src/components/atoms/Buttons/Button/Button.style.ts
  fe/src/components/atoms/Buttons/Button/index.tsx
  fe/src/components/atoms/Icon/IconComponents.tsx
  fe/src/components/atoms/Inputs/ImageInput/index.tsx
  fe/src/components/molecules/Carousel/Carousel.stories.tsx
  fe/src/components/molecules/Carousel/Carousel.style.ts
  fe/src/components/molecules/Carousel/index.tsx
  fe/src/components/molecules/Dropdown/Dropdown.stories.tsx
  fe/src/components/molecules/Dropdown/index.tsx
  fe/src/components/molecules/ImagePreviews/ImagePreviews.stories.tsx
  fe/src/components/molecules/ImagePreviews/ImagePreviews.style.ts
  fe/src/components/molecules/ImagePreviews/index.tsx
  fe/src/components/molecules/ListItem/index.tsx
  fe/src/components/molecules/Navbar/Navbar.style.ts
  fe/src/components/molecules/Navbar/index.tsx
  fe/src/components/molecules/TabBars/DetailTabBar/DetailTabBar.stories.tsx
  fe/src/components/molecules/TabBars/DetailTabBar/DetailTabBar.style.ts
  fe/src/components/molecules/TabBars/DetailTabBar/index.tsx
  fe/src/constants/API.ts
  fe/src/constants/routerPath.ts
  fe/src/index.tsx
  fe/src/pages/Auth/index.tsx
  fe/src/pages/Detail/index.tsx
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Like/index.tsx
  fe/src/pages/Loading/Skeleton/Skeleton.style.ts
  fe/src/pages/Loading/Skeleton/index.jsx
  fe/src/pages/Sale/index.tsx
  fe/src/pages/SalesHistory/index.tsx
  fe/src/styles/PageTemplate.style.ts
  fe/src/type/productsType.ts
Labels: 🧑‍💻 FE, ✨ feat

#250 [FE] Release: 4주차 구현한 내용 release 브랜치에 merge
  fe/src/apis/api/like.ts
  fe/src/apis/api/productDetail.ts
  fe/src/apis/api/sale.ts
  fe/src/apis/api/saleHistory.ts
  fe/src/apis/instances/axiosFetch.ts
  fe/src/assets/Icons/fillHeart.svg
  fe/src/components/Detail/DetailHeader/index.tsx
  fe/src/components/Detail/DetailMain/index.tsx
  fe/src/components/Home/HomeMain/HomeMainHeader/index.tsx
  fe/src/components/Home/HomeMain/HomeMainMain/index.tsx
  fe/src/components/atoms/Icon/IconComponents.tsx
  fe/src/components/molecules/Dropdown/Dropdown.stories.tsx
  fe/src/components/molecules/Dropdown/index.tsx
  fe/src/components/molecules/ListItem/index.tsx
  fe/src/components/molecules/TabBars/DetailTabBar/DetailTabBar.stories.tsx
  fe/src/components/molecules/TabBars/DetailTabBar/DetailTabBar.style.ts
  fe/src/components/molecules/TabBars/DetailTabBar/index.tsx
  fe/src/pages/Detail/index.tsx
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Sale/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#251 [FE] Feat: 준비 페이지 추가 및 배포
  fe/src/App.tsx
  fe/src/apis/api/like.ts
  fe/src/components/Like/LikeHeader/index.tsx
  fe/src/components/Like/LikeMain/LikeMain.style.ts
  fe/src/pages/Detail/index.tsx
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Ready/Ready.style.ts
  fe/src/pages/Ready/index.tsx
  fe/src/utils/convertPriceFormat.ts
Labels: 🧑‍💻 FE, ✨ feat
