Repository masters2023-2nd-project-02/second-hand, pull requests merged in 2023-07, with the labels that each got.

#254 [FE] Merge: dev-fe로 최신 버전 업데이트
  fe/src/App.tsx
  fe/src/apis/api/like.ts
  fe/src/components/Home/TownSetting/TownSettingFooter/index.tsx
  fe/src/components/Like/LikeHeader/index.tsx
  fe/src/components/Like/LikeMain/LikeMain.style.ts
  fe/src/pages/Detail/index.tsx
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Ready/Ready.style.ts
  fe/src/pages/Ready/index.tsx
  fe/src/utils/convertPriceFormat.ts
Labels: 🧑‍💻 FE

#257 [iOS] 홈 화면 상품 목록 띄우기
  ios/SecondHand/SecondHand.xcodeproj/project.pbxproj
  ios/SecondHand/SecondHand/DTO/Product.swift
  ios/SecondHand/SecondHand/Home/HomeViewController.swift
  ios/SecondHand/SecondHand/Home/ImageLabelStackView.swift
  ios/SecondHand/SecondHand/Home/ProductTableViewCell.swift
  ios/SecondHand/SecondHand/Network/ImageCacheManager.swift
  ios/SecondHand/SecondHand/Network/NetworkManager.swift
  ios/SecondHand/SecondHand/Network/URLRequestFactory.swift
  ios/SecondHand/SecondHand/Repository/ProductRepository.swift
  ios/SecondHand/SecondHand/TabBarController.swift
  ios/SecondHand/SecondHand/ViewModel/PastTimeCalculator.swift
  ios/SecondHand/SecondHand/ViewModel/ProductListViewModel.swift
  ios/SecondHand/SecondHand/ViewModel/ProductViewModel.swift
Labels: ✨ feat, 🧑‍💻 iOS

#260 Revert "[iOS] 홈 화면 상품 목록 띄우기"
  ios/SecondHand/SecondHand.xcodeproj/project.pbxproj
  ios/SecondHand/SecondHand/DTO/Product.swift
  ios/SecondHand/SecondHand/Home/HomeViewController.swift
  ios/SecondHand/SecondHand/Home/ImageLabelStackView.swift
  ios/SecondHand/SecondHand/Home/ProductTableViewCell.swift
  ios/SecondHand/SecondHand/Network/ImageCacheManager.swift
  ios/SecondHand/SecondHand/Network/NetworkManager.swift
  ios/SecondHand/SecondHand/Network/URLRequestFactory.swift
  ios/SecondHand/SecondHand/Repository/ProductRepository.swift
  ios/SecondHand/SecondHand/TabBarController.swift
  ios/SecondHand/SecondHand/ViewModel/PastTimeCalculator.swift
  ios/SecondHand/SecondHand/ViewModel/ProductListViewModel.swift
  ios/SecondHand/SecondHand/ViewModel/ProductViewModel.swift
Labels: ✨ feat, 🧑‍💻 iOS

#263 [FE] Feat: Alert(Confirm) 컴포넌트 구현
  fe/public/index.html
  fe/src/components/Home/HomeMain/HomeMainHeader/index.tsx
  fe/src/components/Home/TownSearching/TownSearchingHeader/index.tsx
  fe/src/components/Home/TownSetting/TownSettingFooter/index.tsx
  fe/src/components/molecules/Dialog/Dialog.style.ts
  fe/src/components/molecules/Dialog/index.tsx
  fe/src/components/molecules/Dropdown/Dropdown.stories.tsx
  fe/src/components/molecules/Dropdown/index.tsx
  fe/src/components/molecules/Modal/index.tsx
  fe/src/components/portals/DialogPortal/index.tsx
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Home/TownSearching/index.tsx
  fe/src/styles/GlobalStyles.style.ts
Labels: 🧑‍💻 FE, ✨ feat

#268 [FE] Feat: Modal 컴포넌트
  fe/public/index.html
  fe/src/apis/api/like.ts
  fe/src/apis/api/productDetail.ts
  fe/src/apis/api/saleHistory.ts
  fe/src/apis/instances/axiosFetch.ts
  fe/src/assets/Icons/chevronUp.svg
  fe/src/components/Detail/DetailHeader/DetailHeader.style.ts
  fe/src/components/Detail/DetailHeader/index.tsx
  fe/src/components/Detail/DetailMain/DetailMain.style.ts
  fe/src/components/Detail/DetailMain/index.tsx
  fe/src/components/SalesHistory/SalesHistoryMain/index.tsx
  fe/src/components/atoms/Icon/IconComponents.tsx
  fe/src/components/molecules/ListItem/index.tsx
  fe/src/components/molecules/Modal/Modal.stories.tsx
  fe/src/components/molecules/Modal/Modal.style.ts
  fe/src/components/molecules/Modal/index.tsx
  fe/src/components/molecules/StatusModal/StatusModal.stories.tsx
  fe/src/components/molecules/StatusModal/StatusModal.style.ts
  fe/src/components/molecules/StatusModal/index.tsx
  fe/src/components/molecules/TabBars/DetailTabBar/index.tsx
  fe/src/pages/Detail/index.tsx
  fe/src/pages/SalesHistory/index.tsx
  fe/src/type/productsType.ts
Labels: 🧑‍💻 FE, ✨ feat

#284 [FE] Feat: 카카오 로그인 추가
  fe/src/assets/Icons/github.svg
  fe/src/assets/Icons/kakao.svg
  fe/src/components/Login/LoginMain/LoginMain.style.ts
  fe/src/components/Login/LoginMain/index.tsx
  fe/src/components/atoms/Icon/IconComponents.tsx
  fe/src/constants/API.ts
  fe/src/pages/Auth/index.tsx
  fe/src/pages/Home/TownSearching/index.tsx
  fe/src/pages/Login/index.tsx
Labels: 🧑‍💻 FE, ✨ feat, ♻️ refactoring

#286 현재까지 진행 내용 release 브랜치로 merge
  fe/public/index.html
  fe/src/apis/api/like.ts
  fe/src/apis/api/productDetail.ts
  fe/src/apis/api/saleHistory.ts
  fe/src/apis/instances/axiosFetch.ts
  fe/src/assets/Icons/chevronUp.svg
  fe/src/assets/Icons/github.svg
  fe/src/assets/Icons/kakao.svg
  fe/src/components/Detail/DetailHeader/DetailHeader.style.ts
  fe/src/components/Detail/DetailHeader/index.tsx
  fe/src/components/Detail/DetailMain/DetailMain.style.ts
  fe/src/components/Detail/DetailMain/index.tsx
  fe/src/components/Home/HomeMain/HomeMainHeader/index.tsx
  fe/src/components/Home/TownSearching/TownSearchingHeader/index.tsx
  fe/src/components/Home/TownSetting/TownSettingFooter/index.tsx
  fe/src/components/Like/LikeHeader/index.tsx
  fe/src/components/Login/LoginMain/LoginMain.style.ts
  fe/src/components/Login/LoginMain/index.tsx
  fe/src/components/SalesHistory/SalesHistoryMain/index.tsx
  fe/src/components/atoms/Icon/IconComponents.tsx
  fe/src/components/molecules/Dialog/Dialog.style.ts
  fe/src/components/molecules/Dialog/index.tsx
  fe/src/components/molecules/Dropdown/Dropdown.stories.tsx
  fe/src/components/molecules/Dropdown/index.tsx
  fe/src/components/molecules/ListItem/index.tsx
  fe/src/components/molecules/Modal/Modal.stories.tsx
  fe/src/components/molecules/Modal/Modal.style.ts
  fe/src/components/molecules/Modal/index.tsx
  fe/src/components/molecules/StatusModal/StatusModal.stories.tsx
  fe/src/components/molecules/StatusModal/StatusModal.style.ts
  fe/src/components/molecules/StatusModal/index.tsx
  fe/src/components/molecules/TabBars/DetailTabBar/index.tsx
  fe/src/components/portals/DialogPortal/index.tsx
  fe/src/constants/API.ts
  fe/src/pages/Auth/index.tsx
  fe/src/pages/Detail/index.tsx
  fe/src/pages/Home/HomeMain/index.tsx
  fe/src/pages/Home/TownSearching/index.tsx
  fe/src/pages/Login/index.tsx
  fe/src/pages/SalesHistory/index.tsx
  fe/src/styles/GlobalStyles.style.ts
  fe/src/type/productsType.ts
Labels: 🔧 chore, 🧑‍💻 FE
